CREATE TABLE "users" (
	"u_code" varchar(25) PRIMARY KEY NOT NULL,
	"u_name" varchar(255),
	"u_first_name" varchar(100),
	"u_last_name" varchar(100),
	"u_middle_name" varchar(100),
	"u_nickname" varchar(50),
	"u_dob" date,
	"u_gender" varchar(20),
	"u_email" varchar(255),
	"u_phone_number" varchar(20),
	"u_password_hash" varchar(255),
	"u_password_confirm_hash" varchar(255),
	"u_two_factor_enabled" boolean DEFAULT false NOT NULL,
	"u_two_factor_secret" varchar(255),
	"u_is_active" boolean DEFAULT true NOT NULL,
	"u_is_verified" boolean DEFAULT false NOT NULL,
	"u_email_verified_at" timestamp,
	"u_phone_verified_at" timestamp,
	"u_last_login_at" timestamp,
	"u_profile_picture" text,
	"u_bio" text,
	"u_language" varchar(10) DEFAULT 'en',
	"u_timezone" varchar(50),
	"u_preferences" text,
	"u_address" text,
	"u_city" varchar(100),
	"u_state" varchar(100),
	"u_country" varchar(100),
	"u_zip_code" varchar(20),
	"u_password_reset_token" varchar(255),
	"u_password_reset_expires" timestamp,
	"u_email_verification_token" varchar(255),
	"u_created_at" timestamp DEFAULT now() NOT NULL,
	"u_last_created_by" varchar(25),
	"u_last_update_at" timestamp DEFAULT now() NOT NULL,
	"u_notes" text
);
